import type { Subscription } from "./firefly/subscription-types.ts";

// Only these messages are generated by Ember. Firefly names, descriptions and notes
// never pass through translation replacements.
const budgetNotes: Record<string, string> = {
  "No limit or spending reported for this month.": "Geen budgetbedrag of uitgaven bekend voor deze maand.",
  "No limit set for this currency and month.": "Geen budgetbedrag ingesteld voor deze valuta en maand.",
  "Limits do not form one exact calendar month; monthly comparison unavailable.": "De budgetperiode wijkt af van deze kalendermaand. Vergelijken is niet mogelijk.",
  "Firefly did not report a limit amount.": "Het budgetbedrag is niet beschikbaar.",
  "Firefly did not report spending in this currency; comparison unavailable.": "Uitgaven in deze valuta zijn niet beschikbaar. Vergelijken is niet mogelijk.",
};
export const budgetNote = (note: string) => budgetNotes[note] ?? "Onvoldoende gegevens om dit budget te vergelijken.";

export function subscriptionFrequency(item: Subscription): string {
  if (!item.frequency) return "Niet beschikbaar";
  // Recurrence descriptions are supplied by Firefly and must be preserved verbatim.
  if (item.model !== "bill") return item.frequency;
  const labels: Record<string, string> = { Weekly: "Wekelijks", Monthly: "Maandelijks", Quarterly: "Per kwartaal", "Every half year": "Halfjaarlijks", Yearly: "Jaarlijks" };
  const [frequency, skip] = item.frequency.split(" · ");
  if (!skip) return labels[frequency] ?? item.frequency;
  if (skip === "skip interval unavailable") return `${labels[frequency]} · tussenperiode onbekend`;
  const match = /^skip (\d+) occurrences? between payments$/.exec(skip);
  return match ? `${labels[frequency]} · ${match[1]} keer overslaan tussen betalingen` : item.frequency;
}
export function sortedSubscriptions(items: Subscription[]): Subscription[] {
  return [...items].sort((a, b) => {
    const left = a.active === true ? a.nextDate : null, right = b.active === true ? b.nextDate : null;
    return left && right ? left.localeCompare(right) : left ? -1 : right ? 1 : 0;
  });
}

export function descriptionPreview(description: string): string {
  // Truncate without interpreting SEPA fields or rewriting the original text.
  const characters = Array.from(description);
  return characters.length > 100 ? `${characters.slice(0, 100).join("")}…` : description;
}
